version: '3.8'
services:
  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    networks:
      - backend-network

  backend:
    build: ./
    # container_name: forum-api
    # ports:
    #   - '3333:3333'
    environment:
      - DATABASE_URL=postgresql://postgres:docker@nest-clean-pg:5432/postgres?schema=public
      - PORT=3333
      - JWT_PRIVATE_KEY=
      - JWT_PUBLIC_KEY=
    depends_on:
      - postgres
    networks:
      - backend-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    ports:
      - '3333:3333'
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge
